[package]
name = "openvm-reth-benchmark"
edition.workspace = true
repository.workspace = true
homepage.workspace = true
exclude.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
url.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
dotenv = "0.15.0"
clap = { version = "4.5.7", features = ["derive", "env"] }
clap_builder = "4.5.34"
bincode = { workspace = true, features = ["std"] }
bitcode.workspace = true
hex = "0.4.3"
serde_json.workspace = true
eyre.workspace = true
tokio.workspace = true

# workspace
openvm-stateless-executor.workspace = true
openvm-stateless-witness.workspace = true
openvm-rpc-proxy.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-client.workspace = true
alloy-transport.workspace = true

# reth
reth-primitives.workspace = true
reth-chainspec.workspace = true
reth-evm-ethereum.workspace = true

# openvm
openvm = { workspace = true }
openvm-transpiler = { workspace = true }
openvm-circuit = { workspace = true }
openvm-native-circuit = { workspace = true }
openvm-benchmarks-prove = { workspace = true, features = ["parallel"] }
openvm-stark-sdk = { workspace = true }
openvm-sdk = { workspace = true }
toml.workspace = true

# halo2
halo2-axiom = { version = "0.5.0", default-features = false, optional = true }

[package.metadata.cargo-machete]
ignored = ["halo2-axiom"]

[features]
default = ["jemalloc", "metrics"]
metrics = ["openvm-benchmarks-prove/metrics"]
tco = ["openvm-sdk/tco"]
aot = ["openvm-sdk/aot"]
evm-prove = ["openvm-sdk/evm-prove", "halo2-axiom"]
evm-verify = ["evm-prove", "openvm-sdk/evm-verify", "halo2-axiom"]
perf-metrics = ["openvm-sdk/perf-metrics", "openvm-benchmarks-prove/perf-metrics"]
mimalloc = ["openvm-benchmarks-prove/mimalloc"]
jemalloc = ["openvm-benchmarks-prove/jemalloc"]
# x86 only:
halo2-asm = ["halo2-axiom?/asm"]
cuda = [
    "openvm-native-circuit/cuda",
    "openvm-sdk/cuda",
]
unprotected = ["openvm-sdk/unprotected"]
